#dev
version: '3'
services:
  nakama:
    build: .
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address   postgres:moeen777@192.168.1.100:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address   postgres:moeen777@192.168.1.100:5432/nakama
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

# debug
#version: '3.9'
#services:
#  postgres:
#    container_name: game_backend_postgres
#    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
#    environment:
#      - POSTGRES_DB=nakama
#      - POSTGRES_PASSWORD=localdb
#    expose:
#      - "8080"
#      - "5432"
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "nakama" ]
#      interval: 3s
#      timeout: 3s
#      retries: 5
#    image: postgres:12.2-alpine
#    ports:
#      - "5432:5432"
#      - "8080:8080"
#    volumes:
#      - data:/var/lib/postgresql/data
#
#  nakama:
#    build: .
#    container_name: game_backend
#    entrypoint:
#      - "/bin/sh"
#      - "-ecx"
#      - >
#        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
#        /nakama/dlv --log --log-output=debugger --listen=:4000 --headless=true --api-version=2 exec nakama -- --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama
#    depends_on:
#      postgres:
#        condition: service_healthy
#    expose:
#      - "7349"
#      - "7350"
#      - "7351"
#    healthcheck:
#      test: ["CMD", "/nakama/nakama", "healthcheck"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    links:
#      - "postgres:db"
#    ports:
#      - "7349:7349"
#      - "7350:7350"
#      - "7351:7351"
#      - "2345:2345"
#      - "4000:4000"
#    restart: unless-stopped
#    security_opt:
#      - "seccomp:unconfined"
#    stdin_open: true
#    tty: true
#volumes:
#  data:
